#Название рабочего процесса
name: CI/CD Pipeline

#Триггеры запуска сборки:
on:
  #При пуше в ветку
  push:    
    #Список веток
    branches: [ main ]

#Определение заданий
jobs:
  #Задание для сборки
  build:
    #Запуск на Ubuntu
    runs-on: ubuntu-latest  
    

    #Шаги выполнения задания
    steps:

    #Получение кода из репозитория
    - uses: actions/checkout@v4