#Название рабочего процесса
name: CI/CD Pipeline

#Триггеры запуска сборки:
on:
  #При пуше в ветку
  push:    
    #Список веток
    branches: [ main ]

#Определение заданий
jobs:
  #Задание для сборки
  build:
    #Запуск на собственных серверах
    runs-on: self-hosted

    #Шаги выполнения задания
    steps:
    #Получение кода из репозитория
    - name: Git pull in target directory
      #Переход в папку и копирование файлов
      run: |
        cd C:/Insania/Insania.Web && git pull origin main