#Название рабочего процесса
name: CI/CD Pipeline

#Триггеры запуска сборки:
on:
  #При пуше в ветку
  push:    
    #Список веток
    branches: [ main ]

#Определение заданий
jobs:
  #Задание для сборки
  build:
    #Запуск на собственных серверах
    runs-on: self-hosted

    #Шаги выполнения задания
    steps:
    #Добавление папки в безопасные директории
    - name: Configure git safe directory
      run: git config --global --add safe.directory C:/Insania/Insania.Web
      shell: bash -l {0}
    #Получение кода из репозитория
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: C:/Insania/Insania.Web
        ref: main