#Название рабочего процесса
name: CI/CD Pipeline

#Триггеры запуска сборки:
on:
  #При пуше в ветку
  push:    
    #Список веток
    branches: [ main ]

#Определение заданий
jobs:
  #Задание для сборки
  build:
    #Запуск на собственных серверах
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [insania-linux-server, insania-windows-server]

    #Шаги выполнения задания
    steps:
    #Переход в рабочую директорию и обновление кода
    - name: Update code
      run: |
        cd "$WORKDIR"
        cd Insania.Web
        git pull
      shell: bash

    #Остановка контейнера
    - name: Stop container
      run: |
        cd "$WORKDIR"
        docker-compose stop insania_web
      shell: bash

    #Сборка контейнера
    - name: Build container
      run: |
        cd "$WORKDIR"
        docker-compose build insania_web
      shell: bash

    #Запуск контейнера
    - name: Start container
      run: |
        cd "$WORKDIR"
        docker-compose up -d insania_web
      shell: bash

    #Проверка статуса контейнера
    - name: Verify container status
      run: |
        cd "$WORKDIR"

        #Ожидание перед проверкой
        if [ "$RUNNER_OS" == "Windows" ]; then
          #Для Windows - PowerShell синтаксис
          Start-Sleep -Seconds 10
          $status = docker-compose ps insania_web
          Write-Host "Container status: $status"
          
          if ($status -like "*Up*") {
            Write-Host "✅ Container is running successfully!"
            docker-compose ps
          } else {
            Write-Host "❌ Container failed to start"
            docker-compose logs insania_web --tail=20
            exit 1
          }
        else
          #Для Linux - bash синтаксис
          sleep 10
          status=$(docker-compose ps insania_web)
          echo "Container status: $status"
          
          if echo "$status" | grep -q "Up"; then
            echo "✅ Container is running successfully!"
            docker-compose ps
          else
            echo "❌ Container failed to start"
            docker-compose logs insania_web --tail=20
            exit 1
          fi
        fi
      shell: bash