#Название рабочего процесса
name: CI/CD Pipeline

#Триггеры запуска сборки:
on:
  #При пуше в ветку
  push:    
    #Список веток
    branches: [ main ]

#Определение заданий
jobs:
  #Задание для сборки
  build:
    #Запуск на собственных серверах
    runs-on: self-hosted

    #Шаги выполнения задания
    steps:
    #Получение кода из репозитория
    - name: Checkout code
      #Переход в папку и копирование файлов
      run: |
        cd C:/Insania/Insania.Web
        git pull origin main
    #Остановка контейнера
    - name: Stop container
      run: |
        cd C:/Insania
        docker-compose stop insania_web
    #Сборка контейнера
    - name: Build container
      run: |
        cd C:/Insania
        docker-compose build insania_web
    #Запуск контейнера
    - name: Start container
      run: |
        cd C:/Insania
        docker-compose up -d insania_web
    #Проверка статуса
    - name: Verify container status
      run: |
        cd C:/Insania
        #Ожидание перед проверкой
        Start-Sleep -Seconds 10
        
        #Проверка окончательного статуса
        $status = docker-compose ps insania_web
        Write-Host "Container status: $status"
        
        if ($status -like "*Up*") {
            Write-Host "✅ Container is running successfully!"
            #Показ детальной информации
            docker-compose ps
        } else {
            Write-Host "❌ Container failed to start"
            #Показ логов для диагностики
            docker-compose logs insania_web --tail=20
            exit 1
        }